### ISSUE TITLE
Missing Documentation for getPriceHistory

### ISSUE THREAD

**Issue by majorsauce** [peterszombati/xapi-node#19]
Hey,

seems like there´s no documentation for the "getPriceHistory()" response type.
You´ll get a two-dimensional number array (number[][]) for the candles but I could not find any reference to what the array values represent.

I checked your code and found the candle data is:
Index 0: timestamp
Index 1: open
Index 2: close
Index 3: low
Index 4: high
Index 5: volume

Maybe even returning an array of candle objects instead of the number array would be a great move.

**Comment by peterszombati** [comment]
https://github.com/peterszombati/xapi-node/commit/d2f6a93dec62984ecb792701921d9b7ab6f9dc33
will be published in a new version later
