### ISSUE TITLE
streamSessionId available from login?

### ISSUE THREAD

**Issue by stav** [peterszombati/xapi-node#24]
The XAPI [documentation](http://developers.xstore.pro/documentation/#login) says:

> After successful login the system responds with the status message that can contain the String representing `streamSessionId` field:

	{
		"status": true,
		"streamSessionId": "8469308861804289383"
	}

Are we able to get this information?

**Comment by peterszombati** [comment]
Hi, yes

in code

`
const x = new XAPI(...)
console.log(x.Stream.session)
`

**Comment by stav** [comment]
Ah ok, thanks.  It looks like `Stream.listen.getKeepAlive` is already passing that for us as well.
