### ISSUE TITLE
issue with node 18

### ISSUE THREAD

**Issue by marius-oprea** [peterszombati/xapi-node#27]
In package.json, have installed xapi-node version 2.5.5, on node 18.10.0
I run the command: npm start and got this issue:

...\node_modules\xapi-node\build\core\Socket\SocketConnection.js:147
            if (retries > 0 && e.reason.code !== Enum_1.errorCode.XAPINODE_1 && e.reason.code !== Enum_1.errorCode.BE005) {
                                        ^

TypeError: Cannot read properties of undefined (reading 'code')
    at ...\node_modules\xapi-node\build\core\Socket\SocketConnection.js:147:41

**Comment by peterszombati** [comment]
fixed in 2.5.6, if still there is the error please reopen the ticket and add more info

**Comment by marius-oprea** [comment]
> 

now it's working as expected. thank you.
