### ISSUE TITLE
getCommissionDef

### ISSUE THREAD

**Issue by marius-oprea** [peterszombati/xapi-node#29]
If I want to get the exchange rate from the input symbol to my account currency(different from USD)
getCommissionDef always get as response commission = 0 and rateOfExchange = 1, no matter what symbol or volume I input.
Is the same on https://playground.xapi.pro/login . 
So for sure is not a bug of xapi-node, but the method doesn't seems to work as expected.

**Comment by peterszombati** [comment]
example ?
