### ISSUE TITLE
[question] getPriceHistory "start" parametters

### ISSUE THREAD

**Issue by dawadam** [peterszombati/xapi-node#31]
Hi, thanks for great job.
How get candles from the past with "start" time ?

**Comment by peterszombati** [comment]
Hi,

https://github.com/peterszombati/xapi-node/blob/a9a9be76b6f702831ebafb2d57474f42eddbcf6c/src/v2/core/XAPI.ts#LL145C4-L155C7

simple startUTC as number like example

startUTC: new Date('2023-06-01T18:00:00.000Z').getTime()

**Comment by dawadam** [comment]
Ok, thanks, why this method is not on documentation ?
