### ISSUE TITLE
[feature] getAllSymbols

### ISSUE THREAD

**Issue by dawadam** [peterszombati/xapi-node#32]
Hi,
How to get the list of symbols?
On the documentation, the "getAllSymbols" method exists.

**Comment by peterszombati** [comment]
Hi
I recommend to use webstorm https://www.jetbrains.com/webstorm/promo/

![image](https://github.com/peterszombati/xapi-node/assets/14093029/7907218c-aa4e-4009-94e9-2d3beb8dad47)
![image](https://github.com/peterszombati/xapi-node/assets/14093029/0c90415c-be20-4cc4-bfac-d1482bd82c78)

**Comment by dawadam** [comment]
Webstorm has a good reputation, thank you.
I'm using VS Code, it works fine.

![image](https://github.com/peterszombati/xapi-node/assets/12351787/1dadfced-3671-42aa-91e9-879efeca0089)

I recommend clearing up the documentation a bit.

**Comment by dawadam** [comment]
Of course, I understand, it's a very generous approach. Thank you.
I'll see to do a pull request on the readme or an example, something.
