### ISSUE TITLE
This actually does not work on frontend.

### ISSUE THREAD

**Issue by Earu** [peterszombati/xapi-node#33]
Claim:
![image](https://github.com/peterszombati/xapi-node/assets/20880060/1aa35831-6de2-4187-9aa9-bb6744a69f49)

Result:
![image](https://github.com/peterszombati/xapi-node/assets/20880060/435fc422-05cf-4cb5-b0a6-c3c26a291081)

**Comment by peterszombati** [comment]
did you tried with react ?

**Comment by Earu** [comment]
Yeah this is a react project.
I'm just building using `react-scripts build`

![image](https://github.com/peterszombati/xapi-node/assets/20880060/1dc7f268-fb80-46c3-a382-d38b9f7ed2fc)

**Comment by peterszombati** [comment]
react-scripts build --no-source-map

I know what can be the problem, fast solution can be this command

**Comment by peterszombati** [comment]
2.8.0: logger4 dependency removed
