### ISSUE TITLE
indended to be used with logger4?

### ISSUE THREAD

**Issue by maiopirata** [peterszombati/xapi-node#4]
Hello, nice package!

when I connect it with my account I get this message
```[xapi-node]: Logger path is not defined```

Should you update the docs to explain why this happen? and if one is expected to use your logger package with this?

**Comment by peterszombati** [comment]
Hi! You can solve this by this code:

```ts
const logger = new Logger4({
    path: path.join(process.cwd(), 'logs'), // log files directory path
    directorySizeLimitMB: null
});

const x = new XAPI({
    ...loginConfig,
    logger
});
```

This happens because you are using NodeJS and Log directory is not configured for saving logs.
Later will be available for other log modules.

**Comment by peterszombati** [comment]
@maiopirata  https://github.com/peterszombati/xapi-node#how-to-use-other-log-modules-than-logger4

**Comment by maiopirata** [comment]
@peterszombati Thanks a lot! I will have a test in the next days.
