### ISSUE TITLE
bfb connection details

### ISSUE THREAD

**Issue by bda2206** [peterszombati/xapi-node#6]
Hi Peter,

xtb won't accept Australian clients. do you know the bfb server name(s) for auth/connect?

thanks !

**Comment by peterszombati** [comment]
Hi @bda2206 

bfb use default ws xapi domain, so you dont have to define 'host' param

```ts
new XAPI({
    accountId: '(xStation5) accountID',
    password: '(xStation5) password',
    type: 'real' // or demo
});
```

**Comment by bda2206** [comment]
thanks Peter.
