### ISSUE TITLE
[REAL ACCOUNT] EX017 - You are trying to login using the account from a different platform

### ISSUE THREAD

**Issue by SilvioLuis** [peterszombati/xapi-node#9]
First, I want to thank you very much for this repository, it has helped me a lot!

I created an application that uses this module, and in DEMO it works perfectly.

However, when you put the actual data, I get this return:

CODE:
```
const x = new XAPI({
    accountId: '.....',
    password: '...',
    type: 'real',
  });
```
RETURN: 
```
{
 code: 'EX017',
 explain: 'You are trying to login using the account from a different platform'
}
```

**Comment by artursobon** [comment]
Myabe your real account was created for MetaTrader 4 platform?

**Comment by peterszombati** [comment]
@SilvioLuis 
If you are using with XTB account, you use like this
```ts
const x = new XAPI({
    accountId: '...',
    password: '...',
    host: 'ws.xtb.com', // only for XTB accounts
    type: 'real' // or demo
});
```

**Comment by SilvioLuis** [comment]
> @SilvioLuis
> If you are using with XTB account, you should use like this
> 
> ```ts
> const x = new XAPI({
>     accountId: '...',
>     password: '...',
>     host: 'ws.xtb.com', // only for XTB accounts
>     type: 'real' // or demo
> });
> ```

Thx!!!!
